using MyVirtualPet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyVirtualPet.Services
{
    /// <summary>
    /// Interface for a service to create and read Users. Deleting them is not yet supported.
    /// </summary>
    public interface IUserService
    {
        /// <summary>
        /// Returns the user with the given unique id.
        /// </summary>
        /// <param name="id">the user's id</param>
        /// <returns>the <c>User</c> entity</returns>
        User GetUser(ulong id);

        /// <summary>
        /// Returns all users in the service app.
        /// </summary>
        /// <returns>a List of <c>User</c></returns>
        List<User> GetUsers();

        /// <summary>
        /// Creates a new user in the service.
        /// Users shall have a valid and unique account name, this is checked before creating them.
        /// </summary>
        /// <param name="user">The partial user entity to create inside the service. The user's ID will be generated by the database.</param>
        /// <returns>The updated <c>User</c> entity</returns>
        User CreateUser(User user);
    }
}
